//! Bit-exact structure optimisations: garbage collection, stream
//! deduplication, private-data stripping, stream recompression and JPEG
//! metadata stripping. Nothing here changes what a page renders to.

use crate::deflate::{self, Effort};
use lopdf::{Dictionary, Document, Object, ObjectId, Stream};
use sha2::{Digest, Sha256};
use std::collections::{HashMap, HashSet};

/// Remove application-private and cosmetic data.
pub fn strip(doc: &mut Document, strip_private: bool, strip_metadata: bool) -> (u64, Vec<String>) {
    let mut removed = 0u64;
    let mut notes = Vec::new();
    let private_keys: &[&[u8]] = if strip_private { &[b"PieceInfo", b"Thumb", b"SpiderInfo", b"OPI"] } else { &[] };
    let meta_keys: &[&[u8]] = if strip_metadata { &[b"Metadata"] } else { &[] };
    let ids: Vec<ObjectId> = doc.objects.keys().copied().collect();
    for id in ids {
        let obj = match doc.objects.get_mut(&id) {
            Some(o) => o,
            None => continue,
        };
        let dict = match obj {
            Object::Dictionary(d) => d,
            Object::Stream(s) => &mut s.dict,
            _ => continue,
        };
        let ty = dict.get(b"Type").and_then(Object::as_name).unwrap_or(b"").to_vec();
        let sub = dict.get(b"Subtype").and_then(Object::as_name).unwrap_or(b"").to_vec();
        let eligible = ty == b"Page" || ty == b"Catalog" || sub == b"Image" || sub == b"Form" || ty == b"Pages";
        if !eligible {
            continue;
        }
        for k in private_keys.iter().chain(meta_keys.iter()) {
            // Keep document-level XMP on the catalog only if not stripping metadata.
            if let Some(old) = dict.remove(k) {
                removed += crate::writer::serialized_len(&old) as u64;
            }
        }
    }
    if strip_metadata {
        // Slim the Info dictionary to the fields a reader actually shows.
        if let Ok(info_id) = doc.trailer.get(b"Info").and_then(Object::as_reference) {
            if let Ok(info) = doc.get_dictionary_mut(info_id) {
                let keep: [&[u8]; 6] = [b"Title", b"Author", b"Subject", b"Keywords", b"CreationDate", b"ModDate"];
                let drop: Vec<Vec<u8>> = info.iter().filter(|(k, _)| !keep.contains(&k.as_slice())).map(|(k, _)| k.clone()).collect();
                for k in drop {
                    info.remove(&k);
                }
            }
        }
        notes.push("XMP metadata and non-essential Info entries removed".into());
    }
    // Always brand the producer; it is informational and tiny.
    if let Ok(info_id) = doc.trailer.get(b"Info").and_then(Object::as_reference) {
        if let Ok(info) = doc.get_dictionary_mut(info_id) {
            info.set("Producer", Object::string_literal(crate::PRODUCER));
        }
    }
    (removed, notes)
}

/// Drop every object not reachable from the trailer. Returns removed count.
pub fn gc(doc: &mut Document) -> usize {
    let mut reachable: HashSet<ObjectId> = HashSet::new();
    let mut stack: Vec<ObjectId> = Vec::new();
    collect_refs(&Object::Dictionary(doc.trailer.clone()), &mut stack);
    while let Some(id) = stack.pop() {
        if !reachable.insert(id) {
            continue;
        }
        if let Some(obj) = doc.objects.get(&id) {
            match obj {
                Object::Stream(s) => {
                    let ty = s.dict.get(b"Type").and_then(Object::as_name).unwrap_or(b"");
                    if ty == b"XRef" || ty == b"ObjStm" {
                        continue;
                    }
                    collect_refs(&Object::Dictionary(s.dict.clone()), &mut stack);
                }
                o => collect_refs(o, &mut stack),
            }
        }
    }
    let before = doc.objects.len();
    doc.objects.retain(|id, obj| {
        if !reachable.contains(id) {
            return false;
        }
        // Old xref/object streams are regenerated by our writer.
        if let Object::Stream(s) = obj {
            let ty = s.dict.get(b"Type").and_then(Object::as_name).unwrap_or(b"");
            if ty == b"XRef" || ty == b"ObjStm" {
                return false;
            }
        }
        if let Object::Dictionary(d) = obj {
            if d.has(b"Linearized") {
                return false;
            }
        }
        true
    });
    doc.trailer.remove(b"Prev");
    doc.trailer.remove(b"XRefStm");
    before - doc.objects.len()
}

fn collect_refs(obj: &Object, out: &mut Vec<ObjectId>) {
    match obj {
        Object::Reference(id) => out.push(*id),
        Object::Array(a) => a.iter().for_each(|o| collect_refs(o, out)),
        Object::Dictionary(d) => d.iter().for_each(|(_, o)| collect_refs(o, out)),
        Object::Stream(s) => s.dict.iter().for_each(|(_, o)| collect_refs(o, out)),
        _ => {}
    }
}

/// Rewrite every reference according to `map` (old → new).
pub fn remap_refs(doc: &mut Document, map: &HashMap<ObjectId, ObjectId>) {
    if map.is_empty() {
        return;
    }
    fn walk(o: &mut Object, map: &HashMap<ObjectId, ObjectId>) {
        match o {
            Object::Reference(id) => {
                if let Some(n) = map.get(id) {
                    *id = *n;
                }
            }
            Object::Array(a) => a.iter_mut().for_each(|o| walk(o, map)),
            Object::Dictionary(d) => d.iter_mut().for_each(|(_, o)| walk(o, map)),
            Object::Stream(s) => s.dict.iter_mut().for_each(|(_, o)| walk(o, map)),
            _ => {}
        }
    }
    for obj in doc.objects.values_mut() {
        walk(obj, map);
    }
    let mut trailer = Object::Dictionary(doc.trailer.clone());
    walk(&mut trailer, map);
    if let Object::Dictionary(d) = trailer {
        doc.trailer = d;
    }
}

/// Merge byte-identical streams (fonts embedded N times, repeated images,
/// ICC profiles). Returns (merged objects, bytes saved).
pub fn dedup_streams(doc: &mut Document) -> (usize, u64) {
    let mut seen: HashMap<[u8; 32], ObjectId> = HashMap::new();
    let mut map: HashMap<ObjectId, ObjectId> = HashMap::new();
    let mut saved = 0u64;
    let mut ids: Vec<ObjectId> = doc.objects.keys().copied().collect();
    ids.sort();
    for id in ids {
        let s = match doc.objects.get(&id) {
            Some(Object::Stream(s)) => s,
            _ => continue,
        };
        // Page content streams are position-dependent only via the page that
        // references them, so merging is safe; but never merge streams that
        // reference other objects differently (dict hash covers that).
        let mut h = Sha256::new();
        let mut dict = s.dict.clone();
        dict.remove(b"Length");
        h.update(crate::writer::serialized_len(&Object::Dictionary(dict.clone())).to_le_bytes());
        let mut dbytes = Vec::new();
        crate::writer::write_object(&mut dbytes, &Object::Dictionary(dict));
        h.update(&dbytes);
        h.update(&s.content);
        let digest: [u8; 32] = h.finalize().into();
        match seen.get(&digest) {
            Some(&canon) => {
                map.insert(id, canon);
                saved += s.content.len() as u64 + dbytes.len() as u64;
            }
            None => {
                seen.insert(digest, id);
            }
        }
    }
    for id in map.keys() {
        doc.objects.remove(id);
    }
    remap_refs(doc, &map);
    (map.len(), saved)
}

/// Re-encode Flate/LZW/uncompressed streams with a stronger encoder; strip
/// ASCII wrappers. Image XObjects are left to the image pipeline.
pub fn recompress_streams(doc: &mut Document, effort: Effort, skip_images: bool) -> (usize, i64) {
    use rayon::prelude::*;
    // Gather candidates first so the expensive encoding runs in parallel.
    let mut work: Vec<(ObjectId, Vec<u8>, usize, bool)> = Vec::new();
    for (&id, obj) in &doc.objects {
        let s = match obj {
            Object::Stream(s) => s,
            _ => continue,
        };
        let sub = s.dict.get(b"Subtype").and_then(Object::as_name).unwrap_or(b"");
        let ty = s.dict.get(b"Type").and_then(Object::as_name).unwrap_or(b"");
        if (skip_images && sub == b"Image") || ty == b"XRef" || ty == b"ObjStm" {
            continue;
        }
        let filters: Vec<Vec<u8>> = s.filters().map(|v| v.iter().map(|f| f.to_vec()).collect()).unwrap_or_default();
        let recodable = filters.iter().all(|f| matches!(f.as_slice(), b"FlateDecode" | b"LZWDecode" | b"ASCII85Decode" | b"Fl" | b"LZW" | b"A85"));
        if !recodable {
            continue;
        }
        if let Ok(plain) = s.get_plain_content() {
            work.push((id, plain, s.content.len(), filters.is_empty()));
        }
    }
    let encoded: Vec<(ObjectId, Vec<u8>, Option<&'static str>, usize)> = work
        .into_par_iter()
        .map(|(id, plain, before, _was_plain)| {
            let candidate = deflate::zlib(&plain, effort);
            // Tiny streams may be smaller uncompressed.
            if candidate.len() + 20 < plain.len() {
                (id, candidate, Some("FlateDecode"), before)
            } else {
                (id, plain, None, before)
            }
        })
        .collect();
    let mut touched = 0usize;
    let mut saved = 0i64;
    for (id, new_content, new_filter, before) in encoded {
        if new_content.len() >= before {
            continue;
        }
        if let Some(Object::Stream(s)) = doc.objects.get_mut(&id) {
            saved += before as i64 - new_content.len() as i64;
            touched += 1;
            for k in [b"DecodeParms".as_slice(), b"DP", b"F", b"DL"] {
                s.dict.remove(k);
            }
            match new_filter {
                Some(f) => s.dict.set("Filter", Object::Name(f.as_bytes().to_vec())),
                None => {
                    s.dict.remove(b"Filter");
                }
            }
            s.set_content(new_content);
        }
    }
    (touched, saved)
}

/// Strip EXIF/XMP/Photoshop/comment segments from DCT (JPEG) image streams.
/// The PDF image dictionary carries the authoritative colour space and size, so
/// APP0 (JFIF), APP2 (ICC) and APP14 (Adobe) are the only segments kept.
pub fn strip_jpeg_metadata(doc: &mut Document) -> (usize, i64) {
    let mut n = 0;
    let mut saved = 0i64;
    for obj in doc.objects.values_mut() {
        let s = match obj {
            Object::Stream(s) => s,
            _ => continue,
        };
        let filters = s.filters().map(|v| v.iter().map(|f| f.to_vec()).collect::<Vec<_>>()).unwrap_or_default();
        if filters.len() != 1 || filters[0] != b"DCTDecode" {
            continue;
        }
        if let Some(stripped) = strip_jpeg_segments(&s.content) {
            if stripped.len() < s.content.len() {
                saved += s.content.len() as i64 - stripped.len() as i64;
                n += 1;
                s.set_content(stripped);
            }
        }
    }
    (n, saved)
}

pub fn strip_jpeg_segments(data: &[u8]) -> Option<Vec<u8>> {
    if data.len() < 4 || data[0] != 0xFF || data[1] != 0xD8 {
        return None;
    }
    let mut out = Vec::with_capacity(data.len());
    out.extend_from_slice(&data[..2]);
    let mut i = 2;
    while i + 4 <= data.len() {
        if data[i] != 0xFF {
            return None;
        }
        let marker = data[i + 1];
        if marker == 0xFF {
            i += 1;
            continue;
        }
        if marker == 0xD9 {
            out.extend_from_slice(&data[i..]);
            return Some(out);
        }
        if marker == 0xDA {
            // Start of scan: everything from here on is entropy-coded data.
            out.extend_from_slice(&data[i..]);
            return Some(out);
        }
        if (0xD0..=0xD7).contains(&marker) || marker == 0x01 {
            out.extend_from_slice(&data[i..i + 2]);
            i += 2;
            continue;
        }
        let len = u16::from_be_bytes([data[i + 2], data[i + 3]]) as usize;
        if len < 2 || i + 2 + len > data.len() {
            return None;
        }
        let keep = match marker {
            0xE0 | 0xE2 | 0xEE => true,   // JFIF, ICC, Adobe
            0xE1..=0xEF | 0xFE => false,  // EXIF/XMP/Photoshop/comments
            _ => true,
        };
        if keep {
            out.extend_from_slice(&data[i..i + 2 + len]);
        }
        i += 2 + len;
    }
    None
}

/// Convenience used by tests and the pipeline.
pub fn stream_bytes(s: &Stream) -> u64 {
    s.content.len() as u64
}

pub fn dict_type(d: &Dictionary) -> &[u8] {
    d.get(b"Type").and_then(Object::as_name).unwrap_or(b"")
}

/// Re-Flate one stream without touching its decoded bytes. Used for images
/// whose *sample values* must stay exactly as they are (colour-key masks).
pub fn recompress_stream(s: &mut Stream, effort: Effort) -> i64 {
    let filters: Vec<Vec<u8>> = s.filters().map(|v| v.iter().map(|f| f.to_vec()).collect()).unwrap_or_default();
    let recodable = filters.iter().all(|f| matches!(f.as_slice(), b"FlateDecode" | b"LZWDecode" | b"ASCII85Decode" | b"Fl" | b"LZW" | b"A85"));
    if !recodable {
        return 0;
    }
    let has_predictor = s.dict.get(b"DecodeParms").ok().and_then(|p| p.as_dict().ok()).map(|d| d.has(b"Predictor")).unwrap_or(false);
    if has_predictor {
        return 0; // keep the predictor layout untouched; not worth the risk
    }
    let plain = match s.get_plain_content() {
        Ok(p) => p,
        Err(_) => return 0,
    };
    let before = s.content.len();
    let candidate = deflate::zlib(&plain, effort);
    if candidate.len() < before {
        for k in [b"DecodeParms".as_slice(), b"DP", b"F", b"DL"] {
            s.dict.remove(k);
        }
        s.dict.set("Filter", Object::Name(b"FlateDecode".to_vec()));
        s.set_content(candidate);
        return before as i64 - s.content.len() as i64;
    }
    0
}

/// Re-serialize page / Form XObject content streams compactly: shortest
/// exact number formatting, single separators, no comments, empty `q Q`
/// pairs dropped. Streams with inline images are left untouched. The
/// minified stream is re-parsed and compared operation by operation before
/// it replaces the original.
pub fn minify_content_streams(doc: &mut Document, _effort: Effort) -> (usize, i64) {
    use lopdf::content::Content;
    use rayon::prelude::*;
    let mut ids: HashSet<ObjectId> = HashSet::new();
    for (_, pid) in doc.get_pages() {
        ids.extend(doc.get_page_contents(pid));
    }
    for (&id, obj) in &doc.objects {
        if let Object::Stream(s) = obj {
            if s.dict.get(b"Subtype").and_then(Object::as_name).unwrap_or(b"") == b"Form" {
                ids.insert(id);
            }
        }
    }
    let work: Vec<(ObjectId, Vec<u8>, usize)> = ids
        .into_iter()
        .filter_map(|id| match doc.objects.get(&id) {
            Some(Object::Stream(s)) => s.get_plain_content().ok().map(|p| (id, p, s.content.len())),
            _ => None,
        })
        .collect();
    let results: Vec<(ObjectId, Vec<u8>, i64)> = work
        .into_par_iter()
        .filter_map(|(id, plain, before)| {
            let ops = Content::decode(&plain).ok()?.operations;
            if ops.iter().any(|o| o.operator == "BI") {
                return None;
            }
            let mut out = Vec::with_capacity(plain.len());
            let mut i = 0;
            while i < ops.len() {
                // Drop empty save/restore pairs.
                if ops[i].operator == "q" && i + 1 < ops.len() && ops[i + 1].operator == "Q" {
                    i += 2;
                    continue;
                }
                for (k, operand) in ops[i].operands.iter().enumerate() {
                    if k > 0 {
                        out.push(b' ');
                    }
                    crate::writer::write_object(&mut out, operand);
                }
                if !ops[i].operands.is_empty() {
                    out.push(b' ');
                }
                out.extend_from_slice(ops[i].operator.as_bytes());
                out.push(b'\n');
                i += 1;
            }
            // Round-trip check: same operators and operands after re-parsing.
            let back = Content::decode(&out).ok()?.operations;
            let expected: Vec<&lopdf::content::Operation> = {
                let mut v = Vec::with_capacity(ops.len());
                let mut i = 0;
                while i < ops.len() {
                    if ops[i].operator == "q" && i + 1 < ops.len() && ops[i + 1].operator == "Q" {
                        i += 2;
                        continue;
                    }
                    v.push(&ops[i]);
                    i += 1;
                }
                v
            };
            if back.len() != expected.len() {
                return None;
            }
            for (a, b) in back.iter().zip(&expected) {
                if a.operator != b.operator || a.operands.len() != b.operands.len() {
                    return None;
                }
                for (x, y) in a.operands.iter().zip(&b.operands) {
                    if !same_operand(x, y) {
                        return None;
                    }
                }
            }
            // Decide with a cheap deflate; the stream is stored *plain* and the
            // recompression stage (which follows) applies the expensive encoder
            // once instead of twice.
            // Compare like with like: both the original and the minified text
            // through the same cheap deflate.
            let _ = before;
            let probe = deflate::zlib_best(&out).len();
            let baseline = deflate::zlib_best(&plain).len();
            if probe < baseline && out.len() < plain.len() {
                Some((id, out, baseline as i64 - probe as i64))
            } else {
                None
            }
        })
        .collect();
    let mut n = 0;
    let mut saved = 0i64;
    for (id, plain, gain) in results {
        if let Some(Object::Stream(s)) = doc.objects.get_mut(&id) {
            saved += gain;
            n += 1;
            s.set_plain_content(plain);
        }
    }
    (n, saved)
}

fn same_operand(a: &Object, b: &Object) -> bool {
    match (a, b) {
        (Object::Real(x), Object::Real(y)) => (x - y).abs() <= 1e-4 * x.abs().max(1.0),
        (Object::Integer(x), Object::Real(y)) | (Object::Real(y), Object::Integer(x)) => (*x as f32 - y).abs() <= 1e-4,
        (Object::Array(x), Object::Array(y)) => x.len() == y.len() && x.iter().zip(y).all(|(p, q)| same_operand(p, q)),
        (Object::Dictionary(x), Object::Dictionary(y)) => x.len() == y.len() && x.iter().all(|(k, v)| y.get(k).map(|w| same_operand(v, w)).unwrap_or(false)),
        _ => a == b,
    }
}
