[package]
name = "pixpin-record"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pixpin-codec = { version = "0.1.0", path = "../pixpin-codec" }
thiserror = "2.0.20"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Media_MediaFoundation", "Win32_System_Com"] }
