// Los textos del editor de notas, los mismos que el de antes (los
// `nota-md-*` del catalogo de PixPin), en los dos idiomas.
const EMOJIS_ES = [
  ['😀', 'Sonrisa'],
  ['😂', 'Risa'],
  ['😍', 'Encanta'],
  ['🙂', 'Bien'],
  ['👍', 'Me gusta'],
  ['👎', 'No me gusta'],
  ['🙏', 'Gracias'],
  ['👏', 'Aplausos'],
  ['🎉', 'Fiesta'],
  ['✅', 'Hecho'],
  ['❌', 'No'],
  ['⚠️', 'Atención'],
  ['❤️', 'Corazón'],
  ['🔥', 'Fuego'],
  ['⭐', 'Estrella'],
  ['💡', 'Idea'],
]

export const TEXTOS = {
  es: {
    notaNueva: 'Nota nueva',
    pista: 'Escribe aquí… o / para ver más',
    compartir: 'Compartir',
    cambiarTitulo: 'Cambiar el título',
    guardar: 'Guardar',
    copiaMd: 'Guardar una copia .md…',
    word: 'Exportar a Word…',
    letraTexto: 'Letra del texto',
    letraTitulos: 'Letra de los títulos',
    tamano: 'Tamaño de la letra',
    pequena: 'Pequeña',
    normal: 'Normal',
    grande: 'Grande',
    muyGrande: 'Muy grande',
    soloEsta: 'Solo en esta nota',
    pistaTamano: 'Ctrl + y Ctrl − cambian de uno en uno · {px} px',
    lista: 'Lista',
    numerada: 'Lista numerada',
    casillas: 'Lista de tareas',
    marcar: 'Marcar o desmarcar la tarea',
    fecha: 'Fecha de hoy',
    pagina: 'Página de un proyecto',
    enlaceHoja: 'Enlace a una hoja',
    documento: 'Documento',
    delChat: 'Del chat',
    audio: 'Audio',
    pistaBarra: 'Escribe / en la nota para ver más',
    titulo: 'Título',
    subtitulo: 'Subtítulo',
    apartado: 'Apartado',
    textoNormal: 'Texto normal',
    cita: 'Cita',
    bloque: 'Bloque de código',
    tabla: 'Tabla',
    imagen: 'Imagen',
    raya: 'Raya',
    negrita: 'Negrita',
    cursiva: 'Cursiva',
    tachado: 'Tachado',
    codigo: 'Código',
    enlace: 'Enlace',
    formula: 'Fórmula',
    quitarFormato: 'Quitar formato',
    cortar: 'Cortar',
    copiar: 'Copiar',
    pegar: 'Pegar',
    filaEncima: 'Insertar fila encima',
    filaDebajo: 'Insertar fila debajo',
    colIzquierda: 'Insertar columna a la izquierda',
    colDerecha: 'Insertar columna a la derecha',
    quitarFila: 'Quitar la fila',
    quitarColumna: 'Quitar la columna',
    quitarTabla: 'Quitar la tabla',
    masFila: '+ Fila',
    menosFila: '− Fila',
    masColumna: '+ Columna',
    menosColumna: '− Columna',
    pistaEnlace: 'Pega o escribe un enlace y pulsa Intro',
    verGrande: 'Ver en grande',
    pequenaFoto: 'Pequeña',
    medianaFoto: 'Mediana',
    grandeFoto: 'Grande',
    alAncho: 'Al ancho de la columna',
    quitarImagen: 'Quitar la imagen',
    abrir: 'Abrir',
    irAlMensaje: 'Ir al mensaje en el chat',
    quitarDeLaNota: 'Quitar de la nota',
    noGuardada: 'No se pudo guardar la nota',
    noAdjuntado: 'No se pudo copiar el archivo junto a la nota.',
    demasiadoGrande: 'Ese archivo pesa demasiado para la nota',
    actualizada: 'Nota actualizada con lo que llegó de otro aparato',
    sinHojas: 'Aún no hay hojas en los proyectos para meter en la nota.',
    comentar: 'Comentar',
    comentarios: 'Comentarios',
    sinComentarios: 'No hay comentarios',
    pistaComentarios: 'Elige un trozo del texto y pulsa Comentar (Ctrl+Alt+M)',
    pistaComentar: 'Escribe un comentario',
    sinAncla: 'Su texto ya no está en la nota',
    responder: 'Responder',
    responderPista: 'Responder…',
    cancelar: 'Cancelar',
    editar: 'Editar',
    borrar: 'Borrar',
    borrarHilo: '¿Borrar el comentario y sus respuestas?',
    resuelto: 'resuelto',
    resolver: 'Resolver',
    editado: 'editado',
    verResueltos: 'Ver resueltos',
    ocultarResueltos: 'Ocultar resueltos',
    sinMensajes: 'El chat de este proyecto no tiene mensajes que meter (una nota suelta no tiene chat).',
    meses: ['ene', 'feb', 'mar', 'abr', 'may', 'jun', 'jul', 'ago', 'sept', 'oct', 'nov', 'dic'],
    emojis: EMOJIS_ES,
  },
  en: {
    notaNueva: 'New note',
    pista: 'Write here… or / for more',
    compartir: 'Share',
    cambiarTitulo: 'Rename',
    guardar: 'Save',
    copiaMd: 'Save a copy as .md…',
    word: 'Export to Word…',
    letraTexto: 'Body font',
    letraTitulos: 'Heading font',
    tamano: 'Font size',
    pequena: 'Small',
    normal: 'Normal',
    grande: 'Large',
    muyGrande: 'Extra large',
    soloEsta: 'Only for this note',
    pistaTamano: 'Ctrl + and Ctrl − change it one by one · {px} px',
    lista: 'List',
    numerada: 'Numbered list',
    casillas: 'Task list',
    marcar: 'Check or uncheck the task',
    fecha: "Today's date",
    pagina: 'Project page',
    enlaceHoja: 'Link to a sheet',
    documento: 'Document',
    delChat: 'From the chat',
    audio: 'Audio',
    pistaBarra: 'Type / in the note for more',
    titulo: 'Title',
    subtitulo: 'Subtitle',
    apartado: 'Section',
    textoNormal: 'Normal text',
    cita: 'Quote',
    bloque: 'Code block',
    tabla: 'Table',
    imagen: 'Image',
    raya: 'Divider',
    negrita: 'Bold',
    cursiva: 'Italic',
    tachado: 'Strikethrough',
    codigo: 'Code',
    enlace: 'Link',
    formula: 'Formula',
    quitarFormato: 'Clear formatting',
    cortar: 'Cut',
    copiar: 'Copy',
    pegar: 'Paste',
    filaEncima: 'Insert row above',
    filaDebajo: 'Insert row below',
    colIzquierda: 'Insert column left',
    colDerecha: 'Insert column right',
    quitarFila: 'Delete row',
    quitarColumna: 'Delete column',
    quitarTabla: 'Delete table',
    masFila: '+ Row',
    menosFila: '− Row',
    masColumna: '+ Column',
    menosColumna: '− Column',
    pistaEnlace: 'Paste or type a link and press Enter',
    verGrande: 'View large',
    pequenaFoto: 'Small',
    medianaFoto: 'Medium',
    grandeFoto: 'Large',
    alAncho: 'Column width',
    quitarImagen: 'Remove image',
    abrir: 'Open',
    irAlMensaje: 'Go to the message in the chat',
    quitarDeLaNota: 'Remove from the note',
    noGuardada: 'Could not save the note',
    noAdjuntado: 'Could not copy the file next to the note.',
    demasiadoGrande: 'That file is too big for the note',
    actualizada: 'Note updated with changes from another device',
    sinHojas: 'There are no sheets in the projects to add yet.',
    comentar: 'Comment',
    comentarios: 'Comments',
    sinComentarios: 'No comments',
    pistaComentarios: 'Select some text and press Comment (Ctrl+Alt+M)',
    pistaComentar: 'Write a comment',
    sinAncla: 'Its text is no longer in the note',
    responder: 'Reply',
    responderPista: 'Reply…',
    cancelar: 'Cancel',
    editar: 'Edit',
    borrar: 'Delete',
    borrarHilo: 'Delete the comment and its replies?',
    resuelto: 'resolved',
    resolver: 'Resolve',
    editado: 'edited',
    verResueltos: 'Show resolved',
    ocultarResueltos: 'Hide resolved',
    sinMensajes: "This project's chat has no messages to add (a loose note has no chat).",
    meses: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    emojis: EMOJIS_ES,
  },
}
