[package]
name = "pixpin-pin"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
pixpin-codec = { version = "0.1.0", path = "../pixpin-codec" }
pixpin-geom = { version = "0.1.0", path = "../pixpin-geom" }
pixpin-motor2d = { version = "0.1.0", path = "../pixpin-motor2d" }
pixpin-render = { version = "0.1.0", path = "../pixpin-render" }
thiserror = "2.0.20"
windows-core = "0.62.2"
tracing = "0.1.41"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_Graphics_Direct3D11", "Win32_Graphics_Direct2D", "Win32_Graphics_Gdi", "Win32_UI_WindowsAndMessaging", "Win32_UI_Input_KeyboardAndMouse", "Win32_System_LibraryLoader", "Win32_UI_Shell", "Win32_UI_Shell_Common", "Win32_Storage_FileSystem", "Win32_UI_Input_Ime", "Win32_System_Com", "Win32_Media_MediaFoundation", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common"] }
